
dist:
name: otelcol-dev-bin
description: Basic OpenTelemetry collector distribution for Developers
output_path: /opt/opentel/collector
otelcol_version: 0.96.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.96.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.96.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.96.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.96.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.96.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.96.0


exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.96.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.96.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.96.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.96.0


connectors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/connector/spanmetricsconnector v0.96.0
  - gomod: github.com/tangentland/intervalLogStats v0.1.14


#replaces:
# a list of "replaces" directives that will be part of the resulting go.mod

# This replace statement is necessary since the newly added component is not found/published to GitHub yet. Replace references to GitHub path with the local path
#- github.com/gord02/exampleconnector => ../intervalLogStats
